## Lightning Talks

| Name                      | Institution         | Title |
|---------------------------|--------------------|---------------------------------------------------------------|
| Angélica Mata             | Fiocruz | [A mechanistic understanding of yellow fever outbreak potential under seasonal variation](slides/Lightning Talk - Fiocruz presentation.pdf) |
| [Lin Wang](https://www.gen.cam.ac.uk/directory/lin-wang)                 | University of Cambridge | [Antigenic mapping of influenza A virus with highly accurate serology titer prediction using pathogen genomics and deep learning](slides/Lin_202503.pdf) |
| [Lars Jakob Andreas Jonnerby](https://www.linkedin.com/in/jakob-jonnerby/?originalSubdomain=uk) | Imperial College London | [Inferring influenza transmission dynamics from population immunity levels](slides/Workshop_Jonnerby_v3.pdf) |
| [Ryan Imrie](https://www.linkedin.com/in/ryanmimrie/?originalSubdomain=uk)                | University of Glasgow | Post-pandemic changes in population immunity have reduced the likelihood of emergence of zoonotic coronaviruses |
| [Carl Andrew Pearson](https://github.com/pearsonca)       | University of North Carolina | [flepiMoP & paramix: Prospects for Modularization of and within Odin/Monty](slides/flepiMoP & paramix_ Prospects for Modularization of and within Odin_Monty.pdf) |
| [Julia Mayer](https://globalhealth.charite.de/en/metas/person/person/address_detail/julia_stephanie_mayer)               | Charité – Universitätsmedizin Berlin | [Optimal immunisation strategies against RSV in children](slides/Lighting talk - J Mayer.pdf) |
| [Juan Vesga](https://www.linkedin.com/in/juan-vesga-96182834/?originalSubdomain=uk)                | UK Health Security Agency | [The transmission dynamics of Norovirus in England: a genotype-specific modelling study](slides/odin_workshop_Noro_JV.pdf) |
| [Thomas E Rawson](https://profiles.imperial.ac.uk/t.rawson)           | Imperial College London | [Modelling H5N1 Influenza in US Dairy Cows](slides/H5N1_Odin_Lightning_Talk.pdf) |


